import sys

def main():
    path = r'c:\Users\tarik\Downloads\Documents\ASTRO\src\App.tsx'
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    mobile_bottom_bar_start = 1027 - 1
    mobile_bottom_bar_end = 1078
    
    top_bar_start = 850 - 1
    top_bar_end = 923
    
    sidebar_start = 240 - 1
    sidebar_end = 848
    
    mobile_bottom_replacement = [
        '      <div className="md:hidden fixed bottom-0 left-0 right-0 h-16 bg-[#090d16]/95 backdrop-blur-2xl border-t border-white/[0.04] z-40 px-2 flex items-center justify-around">\n',
        '        {[\n',
        "          { id: 'dashboard', icon: LayoutDashboard, label: 'Home', color: 'cyan' },\n",
        "          { id: 'live-diagnostics', icon: Activity, label: 'Diagnose', color: 'amber' },\n",
        "          { id: 'birth-chart', icon: Compass, label: 'Chart', color: 'purple' },\n",
        "          { id: 'tools-catalog', icon: Sparkles, label: 'Tools', color: 'emerald' },\n",
        "          { id: 'chat', icon: MessageCircle, label: 'Oracle', color: 'blue' },\n",
        '        ].map(({ id, icon: Icon, label, color }) => (\n',
        '          <button\n',
        '            key={id}\n',
        '            onClick={() => navigateTo(id)}\n',
        '            className={`flex flex-col items-center justify-center w-full h-full py-1 transition-all duration-200 ${\n',
        "              activeTab === id ? `text-${color}-400 font-semibold` : 'text-slate-500 hover:text-slate-300'\n",
        '            }`}\n',
        '          >\n',
        '            <Icon className={`w-5 h-5 transition-all ${activeTab === id ? `text-${color}-400 drop-shadow-[0_0_8px_rgba(6,182,212,0.4)]` : \'\'}`} />\n',
        '            <span className="text-[10px] mt-0.5 tracking-tight">{label}</span>\n',
        '            {activeTab === id && <div className={`w-1 h-1 rounded-full bg-${color}-400 mt-0.5`} />}\n',
        '          </button>\n',
        '        ))}\n',
        '      </div>\n'
    ]
    
    top_bar_replacement = [
        '        {/* Top Bar */}\n',
        '        <header className="h-14 border-b border-white/[0.04] bg-[#090d16]/90 backdrop-blur-2xl flex items-center justify-between px-5 flex-shrink-0">\n',
        '          <div className="flex items-center gap-3">\n',
        '            <button \n',
        '              className="md:hidden text-slate-400 hover:text-white p-1.5 rounded-lg hover:bg-white/[0.05] transition-colors" \n',
        '              onClick={() => setIsSidebarOpen(true)}\n',
        '            >\n',
        '              <Menu className="w-5 h-5" />\n',
        '            </button>\n',
        '            <div className="flex items-center gap-2">\n',
        '              <h1 className="text-sm font-semibold text-slate-200 tracking-tight">\n',
        '                {getPageTitle()}\n',
        '              </h1>\n',
        '            </div>\n',
        '          </div>\n',
        '          <div className="flex items-center gap-2">\n',
        '            <button\n',
        '              onClick={() => setIsCommandPaletteOpen(true)}\n',
        '              className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/[0.04] border border-white/[0.06] text-slate-400 hover:text-white hover:border-white/[0.12] transition-all text-xs"\n',
        '            >\n',
        '              <Search className="w-3.5 h-3.5" />\n',
        '              <span className="hidden sm:inline">Search</span>\n',
        '              <kbd className="bg-white/10 px-1.5 py-0.5 rounded text-[10px] font-mono text-slate-400">⌘K</kbd>\n',
        '            </button>\n',
        '            <button\n',
        "              onClick={() => navigateTo('control-center')}\n",
        '              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/[0.04] transition-colors"\n',
        '              title="Settings"\n',
        '            >\n',
        '              <Wrench className="w-4 h-4" />\n',
        '            </button>\n',
        '            <button\n',
        '              onClick={() => setIsProfileModalOpen(true)}\n',
        '              className="w-8 h-8 rounded-full bg-gradient-to-br from-cosmic-500/30 to-nebula-500/30 text-cosmic-300 flex items-center justify-center text-xs font-bold ring-1 ring-white/10 hover:ring-cosmic-500/30 transition-all"\n',
        '            >\n',
        '              {userProfile.name?.charAt(0).toUpperCase() || <User className="w-4 h-4" />}\n',
        '            </button>\n',
        '          </div>\n',
        '        </header>\n'
    ]
    
    sidebar_replacement = [
        '      {/* Sidebar */}\n',
        '      <aside\n',
        '        className={`fixed md:relative top-0 left-0 h-full w-64 bg-[#090d16]/95 md:bg-transparent backdrop-blur-3xl md:backdrop-blur-none border-r border-white/[0.04] flex flex-col z-50 transition-transform duration-300 ${isSidebarOpen ? \'translate-x-0\' : \'-translate-x-full md:translate-x-0\'}`}\n',
        '      >\n',
        '        {/* Logo area */}\n',
        '        <div className="h-14 flex items-center justify-between px-5 border-b border-white/[0.04] flex-shrink-0">\n',
        '          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigateTo(\'dashboard\')}>\n',
        '            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-cosmic-500/20 to-nebula-500/20 border border-cosmic-500/30 flex items-center justify-center">\n',
        '              <Compass className="w-4 h-4 text-cosmic-400" />\n',
        '            </div>\n',
        '            <span className="font-bold text-sm tracking-wide text-slate-200">\n',
        '              COSMOS <span className="text-cosmic-400 font-light">OMNI</span>\n',
        '            </span>\n',
        '          </div>\n',
        '          <button className="md:hidden p-1 text-slate-500 hover:text-white" onClick={() => setIsSidebarOpen(false)}>\n',
        '            <X className="w-4 h-4" />\n',
        '          </button>\n',
        '        </div>\n',
        '\n',
        '        <nav className="flex-1 overflow-y-auto custom-scrollbar px-3 py-4 space-y-5">\n',
        '          {/* PRIMARY HUB */}\n',
        '          <div className="space-y-0.5">\n',
        '            <button onClick={() => navigateTo(\'dashboard\')} className={`sidebar-item ${activeTab === \'dashboard\' ? \'sidebar-item-active\' : \'\'}`}>\n',
        '              <LayoutDashboard className="w-4 h-4" />\n',
        '              <span>Dashboard</span>\n',
        '            </button>\n',
        '            <button onClick={() => navigateTo(\'live-diagnostics\')} className={`sidebar-item ${activeTab === \'live-diagnostics\' ? \'sidebar-item-active\' : \'\'}`}>\n',
        '              <Activity className="w-4 h-4" />\n',
        '              <span>Live Diagnostics</span>\n',
        '            </button>\n',
        '            <button onClick={() => navigateTo(\'advisor\')} className={`sidebar-item ${activeTab === \'advisor\' ? \'sidebar-item-active\' : \'\'}`}>\n',
        '              <ShieldCheck className="w-4 h-4" />\n',
        '              <span>Life Advisor</span>\n',
        '            </button>\n',
        '            <button onClick={() => navigateTo(\'birth-chart\')} className={`sidebar-item ${activeTab === \'birth-chart\' ? \'sidebar-item-active\' : \'\'}`}>\n',
        '              <Compass className="w-4 h-4" />\n',
        '              <span>Birth Chart</span>\n',
        '            </button>\n',
        '            <button onClick={() => navigateTo(\'chat\')} className={`sidebar-item ${activeTab === \'chat\' ? \'sidebar-item-active\' : \'\'}`}>\n',
        '              <MessageCircle className="w-4 h-4" />\n',
        '              <span>AI Oracle</span>\n',
        '            </button>\n',
        '          </div>\n',
        '\n',
        '          {/* TOOLS & ENGINES */}\n',
        '          <div className="mt-4">\n',
        '            <button onClick={() => toggleGroup(\'tools\')} className="w-full flex items-center justify-between px-3 py-2 group">\n',
        '              <span className="sidebar-section-label">Tools & Engines</span>\n',
        '              <motion.div animate={{ rotate: expandedGroups[\'tools\'] ? 180 : 0 }} transition={{ duration: 0.2 }}>\n',
        '                <ChevronDown className="w-3.5 h-3.5 text-slate-600" />\n',
        '              </motion.div>\n',
        '            </button>\n',
        '            <AnimatePresence>\n',
        '              {expandedGroups[\'tools\'] && (\n',
        '                <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: \'auto\', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.2 }} className="overflow-hidden space-y-0.5 mt-1">\n',
        '                  <button onClick={() => navigateTo(\'remedies\')} className={`sidebar-item ${activeTab === \'remedies\' ? \'sidebar-item-active\' : \'\'}`}><Gem className="w-4 h-4" /><span>Gemstone Remedies</span></button>\n',
        '                  <button onClick={() => navigateTo(\'custom-remedies\')} className={`sidebar-item ${activeTab === \'custom-remedies\' ? \'sidebar-item-active\' : \'\'}`}><HeartHandshake className="w-4 h-4" /><span>Problem Solver</span></button>\n',
        '                  <button onClick={() => navigateTo(\'synastry\')} className={`sidebar-item ${activeTab === \'synastry\' ? \'sidebar-item-active\' : \'\'}`}><Sparkles className="w-4 h-4" /><span>Synastry Matcher</span></button>\n',
        '                  <button onClick={() => navigateTo(\'global-suite\')} className={`sidebar-item ${activeTab === \'global-suite\' ? \'sidebar-item-active\' : \'\'}`}><Globe className="w-4 h-4" /><span>Global Wisdom</span></button>\n',
        '                  <button onClick={() => navigateTo(\'tools-catalog\')} className={`sidebar-item ${activeTab === \'tools-catalog\' ? \'sidebar-item-active\' : \'\'}`}><Sparkles className="w-4 h-4" /><span>150+ Tools</span></button>\n',
        '                  <button onClick={() => navigateTo(\'master-chart\')} className={`sidebar-item ${activeTab === \'master-chart\' ? \'sidebar-item-active\' : \'\'}`}><Compass className="w-4 h-4" /><span>Master Chart</span></button>\n',
        '                  <button onClick={() => navigateTo(\'islamic-astrology\')} className={`sidebar-item ${activeTab === \'islamic-astrology\' ? \'sidebar-item-active\' : \'\'}`}><Moon className="w-4 h-4" /><span>Islamic Sciences</span></button>\n',
        '                  <button onClick={() => navigateTo(\'dream-interpreter\')} className={`sidebar-item ${activeTab === \'dream-interpreter\' ? \'sidebar-item-active\' : \'\'}`}><CloudMoon className="w-4 h-4" /><span>Dream Engine</span></button>\n',
        '                  <button onClick={() => navigateTo(\'problem-solver\')} className={`sidebar-item ${activeTab === \'problem-solver\' ? \'sidebar-item-active\' : \'\'}`}><Zap className="w-4 h-4" /><span>Interactive Tools</span></button>\n',
        '                  <button onClick={() => navigateTo(\'spiritual-traditions\')} className={`sidebar-item ${activeTab === \'spiritual-traditions\' ? \'sidebar-item-active\' : \'\'}`}><ShieldCheck className="w-4 h-4" /><span>Spiritual Beliefs</span></button>\n',
        '                  <button onClick={() => navigateTo(\'consultation-hub\')} className={`sidebar-item ${activeTab === \'consultation-hub\' ? \'sidebar-item-active\' : \'\'}`}><Users className="w-4 h-4" /><span>Consultations</span></button>\n',
        '                </motion.div>\n',
        '              )}\n',
        '            </AnimatePresence>\n',
        '          </div>\n',
        '\n',
        '          {/* STANDALONE TOOLS */}\n',
        '          <div className="mt-4">\n',
        '            <button onClick={() => toggleGroup(\'standalone\')} className="w-full flex items-center justify-between px-3 py-2 group">\n',
        '              <span className="sidebar-section-label">Standalone Tools</span>\n',
        '              <motion.div animate={{ rotate: expandedGroups[\'standalone\'] ? 180 : 0 }} transition={{ duration: 0.2 }}>\n',
        '                <ChevronDown className="w-3.5 h-3.5 text-slate-600" />\n',
        '              </motion.div>\n',
        '            </button>\n',
        '            <AnimatePresence>\n',
        '              {expandedGroups[\'standalone\'] && (\n',
        '                <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: \'auto\', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.2 }} className="overflow-hidden space-y-0.5 mt-1">\n',
        '                  <button onClick={() => navigateTo(\'divisional-charts\')} className={`sidebar-item ${activeTab === \'divisional-charts\' ? \'sidebar-item-active\' : \'\'}`}><Compass className="w-4 h-4" /><span>Divisional Charts</span></button>\n',
        '                  <button onClick={() => navigateTo(\'btr-suite\')} className={`sidebar-item ${activeTab === \'btr-suite\' ? \'sidebar-item-active\' : \'\'}`}><Clock className="w-4 h-4" /><span>Birth Time Rectification</span></button>\n',
        '                  <button onClick={() => navigateTo(\'gemstone-suite\')} className={`sidebar-item ${activeTab === \'gemstone-suite\' ? \'sidebar-item-active\' : \'\'}`}><Gem className="w-4 h-4" /><span>Gemstones</span></button>\n',
        '                  <button onClick={() => navigateTo(\'numerology-suite\')} className={`sidebar-item ${activeTab === \'numerology-suite\' ? \'sidebar-item-active\' : \'\'}`}><Hash className="w-4 h-4" /><span>Numerology</span></button>\n',
        '                  <button onClick={() => navigateTo(\'tarot-iching\')} className={`sidebar-item ${activeTab === \'tarot-iching\' ? \'sidebar-item-active\' : \'\'}`}><Eye className="w-4 h-4" /><span>Tarot & I Ching</span></button>\n',
        '                  <button onClick={() => navigateTo(\'time-horizon\')} className={`sidebar-item ${activeTab === \'time-horizon\' ? \'sidebar-item-active\' : \'\'}`}><Calendar className="w-4 h-4" /><span>Time Horizon</span></button>\n',
        '                  <button onClick={() => navigateTo(\'dosha-engine\')} className={`sidebar-item ${activeTab === \'dosha-engine\' ? \'sidebar-item-active\' : \'\'}`}><AlertTriangle className="w-4 h-4" /><span>Dosha Engine</span></button>\n',
        '                  <button onClick={() => navigateTo(\'biorhythm-tracker\')} className={`sidebar-item ${activeTab === \'biorhythm-tracker\' ? \'sidebar-item-active\' : \'\'}`}><Activity className="w-4 h-4" /><span>Biorhythm Tracker</span></button>\n',
        '                  <button onClick={() => navigateTo(\'chakra-alignment\')} className={`sidebar-item ${activeTab === \'chakra-alignment\' ? \'sidebar-item-active\' : \'\'}`}><Sunrise className="w-4 h-4" /><span>Chakra Alignment</span></button>\n',
        '                  <button onClick={() => navigateTo(\'fengshui-matrix\')} className={`sidebar-item ${activeTab === \'fengshui-matrix\' ? \'sidebar-item-active\' : \'\'}`}><Map className="w-4 h-4" /><span>Feng Shui Matrix</span></button>\n',
        '                  <button onClick={() => navigateTo(\'electional-muhurta\')} className={`sidebar-item ${activeTab === \'electional-muhurta\' ? \'sidebar-item-active\' : \'\'}`}><Clock className="w-4 h-4" /><span>Electional Muhurta</span></button>\n',
        '                  <button onClick={() => navigateTo(\'planetary-horas\')} className={`sidebar-item ${activeTab === \'planetary-horas\' ? \'sidebar-item-active\' : \'\'}`}><Sun className="w-4 h-4" /><span>Planetary Horas</span></button>\n',
        '                  <button onClick={() => navigateTo(\'mantra-soundboard\')} className={`sidebar-item ${activeTab === \'mantra-soundboard\' ? \'sidebar-item-active\' : \'\'}`}><Music className="w-4 h-4" /><span>Mantra Soundboard</span></button>\n',
        '                  <button onClick={() => navigateTo(\'transit-radar\')} className={`sidebar-item ${activeTab === \'transit-radar\' ? \'sidebar-item-active\' : \'\'}`}><Radar className="w-4 h-4" /><span>Transit Radar</span></button>\n',
        '                  <button onClick={() => navigateTo(\'panchang-deities\')} className={`sidebar-item ${activeTab === \'panchang-deities\' ? \'sidebar-item-active\' : \'\'}`}><Calendar className="w-4 h-4" /><span>Panchang & Deities</span></button>\n',
        '                  <button onClick={() => navigateTo(\'cosmic-compass\')} className={`sidebar-item ${activeTab === \'cosmic-compass\' ? \'sidebar-item-active\' : \'\'}`}><Compass className="w-4 h-4" /><span>Cosmic Compass</span></button>\n',
        '                  <button onClick={() => navigateTo(\'astro-cartography\')} className={`sidebar-item ${activeTab === \'astro-cartography\' ? \'sidebar-item-active\' : \'\'}`}><MapPin className="w-4 h-4" /><span>Astro-Cartography</span></button>\n',
        '                  <button onClick={() => navigateTo(\'transit-calendar\')} className={`sidebar-item ${activeTab === \'transit-calendar\' ? \'sidebar-item-active\' : \'\'}`}><Calendar className="w-4 h-4" /><span>Transit Calendar</span></button>\n',
        '                  <button onClick={() => navigateTo(\'synastry-overlay\')} className={`sidebar-item ${activeTab === \'synastry-overlay\' ? \'sidebar-item-active\' : \'\'}`}><Sparkles className="w-4 h-4" /><span>Synastry Overlay</span></button>\n',
        '                  <button onClick={() => navigateTo(\'mind-map\')} className={`sidebar-item ${activeTab === \'mind-map\' ? \'sidebar-item-active\' : \'\'}`}><Network className="w-4 h-4" /><span>Mind Map</span></button>\n',
        '                  <button onClick={() => navigateTo(\'chart-analytics\')} className={`sidebar-item ${activeTab === \'chart-analytics\' ? \'sidebar-item-active\' : \'\'}`}><BarChart2 className="w-4 h-4" /><span>Chart Analytics</span></button>\n',
        '                  <button onClick={() => navigateTo(\'learning-hub\')} className={`sidebar-item ${activeTab === \'learning-hub\' ? \'sidebar-item-active\' : \'\'}`}><BookOpen className="w-4 h-4" /><span>Learning Hub</span></button>\n',
        '                  <button onClick={() => navigateTo(\'report-generator\')} className={`sidebar-item ${activeTab === \'report-generator\' ? \'sidebar-item-active\' : \'\'}`}><FileText className="w-4 h-4" /><span>Report Generator</span></button>\n',
        '                  <button onClick={() => navigateTo(\'admin-dashboard\')} className={`sidebar-item ${activeTab === \'admin-dashboard\' ? \'sidebar-item-active\' : \'\'}`}><Shield className="w-4 h-4" /><span>Admin Dashboard</span></button>\n',
        '                </motion.div>\n',
        '              )}\n',
        '            </AnimatePresence>\n',
        '          </div>\n',
        '\n',
        '          {/* GLOBAL SYSTEMS */}\n',
        '          {Object.entries(groupedTraditions).map(([groupName, traditions]) => (\n',
        '            <div key={groupName} className="mt-4">\n',
        '              <button\n',
        '                onClick={() => toggleGroup(groupName)}\n',
        '                className="w-full flex items-center justify-between px-3 py-2 group"\n',
        '              >\n',
        '                <span className="sidebar-section-label">{groupName}</span>\n',
        '                <motion.div\n',
        '                  animate={{ rotate: expandedGroups[groupName] ? 180 : 0 }}\n',
        '                  transition={{ duration: 0.2 }}\n',
        '                >\n',
        '                  <ChevronDown className="w-3.5 h-3.5 text-slate-600" />\n',
        '                </motion.div>\n',
        '              </button>\n',
        '              <AnimatePresence>\n',
        '                {expandedGroups[groupName] && (\n',
        '                  <motion.div\n',
        '                    initial={{ height: 0, opacity: 0 }}\n',
        '                    animate={{ height: \'auto\', opacity: 1 }}\n',
        '                    exit={{ height: 0, opacity: 0 }}\n',
        '                    transition={{ duration: 0.2 }}\n',
        '                    className="overflow-hidden"\n',
        '                  >\n',
        '                    <div className="space-y-0.5 mt-1">\n',
        '                      {traditions.map((tradition) => (\n',
        '                        <button\n',
        '                          key={tradition.id}\n',
        '                          onClick={() => navigateTo(tradition.id)}\n',
        '                          className={`sidebar-item ${activeTab === tradition.id ? \'sidebar-item-active\' : \'\'}`}\n',
        '                        >\n',
        '                          <span className="text-sm mr-2.5 opacity-80">{tradition.icon}</span>\n',
        '                          <span>{tradition.name}</span>\n',
        '                        </button>\n',
        '                      ))}\n',
        '                    </div>\n',
        '                  </motion.div>\n',
        '                )}\n',
        '              </AnimatePresence>\n',
        '            </div>\n',
        '          ))}\n',
        '        </nav>\n',
        '\n',
        '        {/* Bottom area */}\n',
        '        <div className="p-3 border-t border-white/[0.04] space-y-2">\n',
        '          <div className="rounded-xl p-2.5 bg-white/[0.02] border border-white/[0.04] space-y-2">\n',
        '            <div className="flex items-center gap-3">\n',
        '              <div className="w-9 h-9 rounded-full bg-gradient-to-br from-cosmic-500/30 to-nebula-500/30 text-cosmic-300 flex items-center justify-center shrink-0 text-xs font-bold ring-1 ring-white/10">\n',
        '                {userProfile.name?.charAt(0).toUpperCase() || <User className="w-4 h-4" />}\n',
        '              </div>\n',
        '              <div className="overflow-hidden flex-1">\n',
        '                <p className="text-xs font-semibold text-white truncate">{userProfile.name || \'Seeker\'}</p>\n',
        '                <p className="text-[10px] text-slate-400 truncate capitalize">{userProfile.preferredSystem || \'Western\'} • {userProfile.dob || \'1998-06-15\'}</p>\n',
        '              </div>\n',
        '            </div>\n',
        '            <div className="grid grid-cols-2 gap-1.5 pt-1">\n',
        '              <button\n',
        '                onClick={() => setIsProfileModalOpen(true)}\n',
        '                className="py-1.5 px-2 rounded-lg bg-white/[0.03] hover:bg-white/[0.06] text-slate-300 border border-white/[0.06] text-[10px] font-medium transition-all truncate"\n',
        '              >\n',
        '                Customise\n',
        '              </button>\n',
        '              <button\n',
        '                onClick={() => setIsAuthModalOpen(true)}\n',
        '                className="py-1.5 px-2 rounded-lg bg-white/[0.03] hover:bg-white/[0.06] text-slate-300 border border-white/[0.06] text-[10px] font-medium transition-all truncate"\n',
        '              >\n',
        '                Sign In\n',
        '              </button>\n',
        '            </div>\n',
        '          </div>\n',
        '          <div className="p-2.5 rounded-xl bg-white/[0.02] border border-white/[0.04] text-[10px] space-y-1">\n',
        '            <div className="flex items-center gap-1.5 text-slate-300 font-medium">\n',
        '              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 shrink-0" />\n',
        '              <span>Verified System</span>\n',
        '            </div>\n',
        '            <p className="text-slate-500 leading-tight">\n',
        '              Engineered for absolute accuracy.\n',
        '            </p>\n',
        '          </div>\n',
        '        </div>\n',
        '      </aside>\n'
    ]
    
    expanded_groups_replacement = [
        '  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>({\n',
        "    'tools': false,\n",
        "    'standalone': false,\n",
        "    'Asian & Eastern': false,\n",
        "    'Western & European': false,\n",
        "    'Middle Eastern & Semitic': false,\n",
        "    'Indigenous & Ancient': false\n",
        '  });\n'
    ]
    
    lines[mobile_bottom_bar_start:mobile_bottom_bar_end] = mobile_bottom_replacement
    lines[top_bar_start:top_bar_end] = top_bar_replacement
    lines[sidebar_start:sidebar_end] = sidebar_replacement
    
    for i in range(len(lines)):
        if "const [expandedGroups, setExpandedGroups]" in lines[i]:
            for j in range(i, len(lines)):
                if "});" in lines[j]:
                    lines[i:j+1] = expanded_groups_replacement
                    break
            break

    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)

if __name__ == '__main__':
    main()
