/**
 * ASTRO360 SEO LAB - Multi-Format Report Generator
 * Generates audit exports in Markdown, JSON, and CSV formats.
 */

import { SeoAuditReport } from './types';

export class SeoReportGenerator {
  public static generateMarkdownReport(report: SeoAuditReport): string {
    return `# ASTRO360 SEO LAB AUDIT REPORT
**Target:** ${report.targetUrl}
**Domain:** ${report.domain}
**Date:** ${new Date(report.auditTimestamp).toLocaleString()}
**Overall Health Score:** ${report.overallHealthScore}/100

---

## 1. Executive Summary
- **Total Pages Analyzed:** ${report.totalPagesScanned}
- **Critical Issues (P0):** ${report.criticalIssuesCount}
- **Warnings (P1/P2):** ${report.warningsCount}
- **Passed Checks:** ${report.passedChecksCount}

---

## 2. Issues & Actionable Fixes
${report.issues.map(issue => `
### [${issue.priority}] ${issue.problem}
- **Category:** ${issue.category}
- **Why It Matters:** ${issue.whyItMatters}
- **Recommended Fix:** ${issue.howToFix}
- **Evidence:** ${issue.evidence}
- **Affected URLs:** ${issue.affectedUrls.join(', ')}
- **Status:** ${issue.status}
`).join('\n')}

---

## 3. Core Web Vitals Summary
- **Average LCP:** ${report.performanceSummary.avgLcp}s (Target: < 2.5s)
- **Average INP:** ${report.performanceSummary.avgInp}ms (Target: < 200ms)
- **Average CLS:** ${report.performanceSummary.avgCls} (Target: < 0.1)

---
*Report generated by ASTRO360 SEO LAB — Free Open Technical SEO Intelligence*
`;
  }

  public static generateCsvReport(report: SeoAuditReport): string {
    const headers = 'URL,Status,Title,TitleLength,Description,Canonical,Indexable,LCP,IssuesCount\n';
    const rows = report.pages.map(p => 
      `"${p.url}",${p.httpStatus},"${p.title.replace(/"/g, '""')}",${p.titleLength},"${p.description.replace(/"/g, '""')}",${p.canonicalStatus},${p.indexable},${p.cwv.lcp},${p.issues.length}`
    ).join('\n');
    return headers + rows;
  }
}
