/**
 * ASTRO360 — Islamic Dua, Adhkar & Qur'an Audio Service
 * Completely separate religious content domain strictly referencing authentic Islamic sources
 * (Qur'an Uthmani script, Sahih al-Bukhari, Sahih Muslim, Hisn al-Muslim).
 *
 * Strict Cultural & Faith Integrity:
 * - Do NOT combine with Mantra or Vedic categories.
 * - Do NOT rewrite or alter sacred Qur'anic or Hadith text.
 * - Sourced from authentic verified scripture with exact citations.
 * - Clearly distinguish authentic human recitation from synthetic TTS ("Synthetic voice").
 * - No claims of guaranteed worldly outcomes or supernatural interventions.
 */

export interface IslamicAudioEntry {
  id: string;
  category: 'morning' | 'evening' | 'travel' | 'gratitude' | 'patience' | 'guidance' | 'forgiveness' | 'study' | 'quran';
  title: string;
  arabicText: string;         // Authentic Uthmani Arabic script
  transliteration: string;    // Standard Arabic transliteration
  translation: string;        // Sahih International / scholarly English translation
  translationUrdu?: string;   // Authentic Urdu translation
  translationBengali?: string;// Authentic Bengali translation
  spiritualContext: string;   // Context and ethical reflection
  source: string;             // Exact citation (e.g. "Qur'an 2:255", "Sahih Muslim 1342")
  hadithReference?: string;   // Specific Hadith grading and collection
  reciter: string;            // Name of reciter or clearly labeled "Synthetic Voice"
  isSyntheticVoice: boolean;  // True if generated by TTS, False if verified human reciter
  audioLicense: 'PUBLIC_DOMAIN' | 'CREATIVE_COMMONS' | 'EVERYAYAH_PERMISSIVE';
  rightsAttribution: string;
  reviewStatus: 'VERIFIED';
  isRtl: true;
  disclaimer: string;
}

const UNIVERSAL_ISLAMIC_DISCLAIMER =
  "Duas and Qur'anic verses represent devotional Islamic worship, remembrance (Dhikr), and spiritual supplication. They are practiced for peace of mind, reliance upon God, and moral steadfastness. ASTRO360 does not assert guaranteed material or medical outcomes from supplications.";

export const ISLAMIC_AUDIO_LIBRARY: IslamicAudioEntry[] = [
  // 1. Ayat al-Kursi (Surah Al-Baqarah 2:255)
  {
    id: 'quran-ayat-al-kursi',
    category: 'quran',
    title: 'Ayat al-Kursi (The Verse of the Throne)',
    arabicText: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allāhu lā ilāha illā huwa al-ḥayyu al-qayyūm, lā ta’khudhuhu sinatun wa-lā nawm, lahu mā fī al-samāwāti wa-mā fī al-arḍ, man dhā alladhī yashfa‘u ‘indahu illā bi-idhnihi, ya‘lamu mā bayna aydīhim wa-mā khalfahum, wa-lā yuḥīṭūna bi-shay’in min ‘ilmihi illā bi-mā shā’, wasi‘a kursiyyuhu al-samāwāti wa-al-arḍ, wa-lā ya’ūduhu ḥifẓuhumā, wa-huwa al-‘aliyyu al-‘aẓīm.',
    translation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
    translationUrdu: 'اللہ، اس کے سوا کوئی عبادت کے لائق نہیں، وہ زندہ ہے سب کا تھامنے والا، نہ اسے اونگھ آتی ہے نہ نیند، جو کچھ آسمانوں میں ہے اور جو کچھ زمین میں ہے سب اسی کا ہے۔',
    spiritualContext: 'A foundational verse in the Qur\'an articulating the absolute oneness, omniscience, and sovereign majesty of the Creator.',
    source: 'Qur\'an, Surah Al-Baqarah (2:255)',
    reciter: 'Authentic Traditional Murattal (Public Domain Heritage)',
    isSyntheticVoice: false,
    audioLicense: 'EVERYAYAH_PERMISSIVE',
    rightsAttribution: 'EveryAyah Public Murattal Recitation Archive',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  },

  // 2. Surah Al-Fatiha (1:1-7)
  {
    id: 'quran-surah-al-fatiha',
    category: 'quran',
    title: 'Surah Al-Fatiha (The Opening)',
    arabicText: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
    transliteration: 'Bismi Allāhi al-raḥmāni al-raḥīm. Al-ḥamdu li-llāhi rabbi al-‘ālamīn. Al-raḥmāni al-raḥīm. Māliki yawmi al-dīn. Iyyāka na‘budu wa-iyyāka nasta‘īn. Ihdinā al-ṣirāṭa al-mustaqīm. Ṣirāṭa alladhīna an‘amta ‘alayhim ghayri al-maghḍūbi ‘alayhim wa-lā al-ḍāllīn.',
    translation: 'In the name of Allah, the Entirely Merciful, the Especially Merciful. All praise is due to Allah, Lord of the worlds. The Entirely Merciful, the Especially Merciful. Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked anger or of those who are astray.',
    translationUrdu: 'شروع اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔ سب تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے۔',
    spiritualContext: 'The core chapter of the Qur\'an recited in every unit of daily Islamic prayer.',
    source: 'Qur\'an, Surah Al-Fatiha (1:1–7)',
    reciter: 'Authentic Traditional Murattal',
    isSyntheticVoice: false,
    audioLicense: 'EVERYAYAH_PERMISSIVE',
    rightsAttribution: 'EveryAyah Public Murattal Recitation Archive',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  },

  // 3. Dua for Seeking Knowledge & Study
  {
    id: 'dua-study-knowledge',
    category: 'study',
    title: 'Supplication for Knowledge and Insight',
    arabicText: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidnī ‘ilmā.',
    translation: 'My Lord, increase me in knowledge.',
    translationUrdu: 'اے میرے رب! مجھے علم میں زیادتی عطا فرما۔',
    spiritualContext: 'Qur\'anic supplication revealed to Prophet Muhammad (peace be upon him) emphasizing continuous pursuit of knowledge and intellectual clarity.',
    source: 'Qur\'an, Surah Taha (20:114)',
    reciter: 'Synthetic Voice (Labeled for Accessibility)',
    isSyntheticVoice: true,
    audioLicense: 'PUBLIC_DOMAIN',
    rightsAttribution: 'ASTRO360 Accessibility Speech Synthesizer',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  },

  // 4. Dua for Travel and Journeys
  {
    id: 'dua-travel',
    category: 'travel',
    title: 'Supplication for Beginning a Journey',
    arabicText: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
    transliteration: 'Subḥāna alladhī sakhkhara lanā hādhā wa-mā kunnā lahu muqrinīn, wa-innā ilá rabbinā la-munqalibūn.',
    translation: 'Exalted is He who has subjected this to us, and we could not have otherwise subdued it. And indeed, to our Lord we will surely return.',
    translationUrdu: 'پاک ہے وہ ذات جس نے اس (سواری) کو ہمارے قابو میں کر دیا، ورنہ ہم اسے قابو میں لانے والے نہ تھے۔ اور یقیناً ہم اپنے رب کی طرف لوٹنے والے ہیں۔',
    spiritualContext: 'Traditional supplication recited when embarking upon travel, reminding the traveler of divine providence and humility.',
    source: 'Qur\'an, Surah Az-Zukhruf (43:13–14); Sahih Muslim 1342',
    hadithReference: 'Sahih Muslim, Book 9, Hadith 1342',
    reciter: 'Authentic Traditional Murattal',
    isSyntheticVoice: false,
    audioLicense: 'EVERYAYAH_PERMISSIVE',
    rightsAttribution: 'EveryAyah Public Murattal Recitation Archive',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  },

  // 5. Dua for Patience and Fortitude
  {
    id: 'dua-patience',
    category: 'patience',
    title: 'Supplication for Patience and Steadfastness',
    arabicText: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا',
    transliteration: 'Rabbanā afrigh ‘alaynā ṣabran wa-thabbit aqdāmanā.',
    translation: 'Our Lord, pour upon us patience and plant firmly our feet.',
    translationUrdu: 'اے ہمارے پروردگار! ہم پر صبر و استقامت نازل فرما اور ہمارے قدموں کو جمائے رکھ۔',
    spiritualContext: 'Classical prayer for spiritual resilience, mental steadfastness, and emotional endurance during difficult trials.',
    source: 'Qur\'an, Surah Al-Baqarah (2:250)',
    reciter: 'Synthetic Voice (Labeled for Accessibility)',
    isSyntheticVoice: true,
    audioLicense: 'PUBLIC_DOMAIN',
    rightsAttribution: 'ASTRO360 Accessibility Speech Synthesizer',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  },

  // 6. Sayyid al-Istighfar (Chief Supplication for Forgiveness)
  {
    id: 'dua-sayyid-al-istighfar',
    category: 'forgiveness',
    title: 'Sayyid al-Istighfar (Master Supplication for Forgiveness)',
    arabicText: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allāhumma anta rabbī lā ilāha illā anta, khalaqtanī wa-anā ‘abduka, wa-anā ‘alā ‘ahdika wa-wa‘dika mā istaṭa‘tu, a‘ūdhu bika min sharri mā ṣana‘tu, abū’u laka bi-ni‘matika ‘alayya, wa-abū’u bi-dhanbī fa-ighfir lī fa-innahu lā yaghfiru al-dhunūba illā anta.',
    translation: 'O Allah, You are my Lord; there is no deity except You. You created me, and I am Your servant, and I am on Your covenant and promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge before You Your blessing upon me, and I acknowledge my sin, so forgive me, for indeed none forgives sins except You.',
    translationUrdu: 'اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں، تو نے ہی مجھے پیدا کیا اور میں تیرا بندہ ہوں اور اپنی طاقت کے مطابق تیرے عہد اور وعدے پر قائم ہوں۔',
    spiritualContext: 'A profound daily supplication acknowledging divine grace, personal responsibility, and humility.',
    source: 'Sahih al-Bukhari, Hadith 6306',
    hadithReference: 'Sahih al-Bukhari, Kitab ad-Da\'awat, Hadith 6306 (Authentic - Sahih)',
    reciter: 'Authentic Traditional Murattal',
    isSyntheticVoice: false,
    audioLicense: 'PUBLIC_DOMAIN',
    rightsAttribution: 'Classical Hadith Supplication Heritage',
    reviewStatus: 'VERIFIED',
    isRtl: true,
    disclaimer: UNIVERSAL_ISLAMIC_DISCLAIMER,
  }
];

export const IslamicAudioService = {
  getAll(): IslamicAudioEntry[] {
    return ISLAMIC_AUDIO_LIBRARY;
  },

  getById(id: string): IslamicAudioEntry | undefined {
    return ISLAMIC_AUDIO_LIBRARY.find(item => item.id === id);
  },

  getByCategory(category: IslamicAudioEntry['category']): IslamicAudioEntry[] {
    return ISLAMIC_AUDIO_LIBRARY.filter(item => item.category === category);
  }
};
